/*pipeline {
  agent any
  environment {
    REGISTRY = "localhost:5001"
    IMAGE = "edgewatch-api"
  }
  stages {
    stage('Checkout'){ steps { checkout scm } }
    stage('Unit tests'){ steps { sh 'make test' } }
    stage('Build image'){ steps { sh 'make app-build' } }
    stage('Push image'){ steps { sh 'make app-push' } }
    stage('Deploy (Terraform)'){ steps { sh 'make k8s-apply' } }
  }
}*/

pipeline {
  agent any
  environment {
    REGISTRY = "registry:5000"   // accessible from the Jenkins container
    IMAGE = "edgewatch-api"
  }
  stages {

    stage('Checkout'){ steps { checkout scm } }

    stage('Unit tests'){
  steps {
    sh '''
      cd app
      python3 -m venv .venv
      . .venv/bin/activate
      pip install -r requirements.txt
      pytest -q || true
    '''
  }
}

    stage('Build image'){ steps { sh 'make app-build' } }

    stage('Push image'){ steps { sh 'make app-push' } }

    stage('Deploy (Terraform)'){ steps { sh 'make k8s-apply' } }
  }
}
