services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports: ["8090:8080","50000:50000"]
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
      - ../:/workspace
volumes: { jenkins_home: {} }
